### ISSUE TITLE
"OSError : No such file or directory" when running fakemenot

### ISSUE THREAD

**Issue by Hori75** [sachinkamath/fakemenot#15]
I tried to run `fakemenot` but the error occured
```
Traceback (most recent call last):
  File "/usr/local/bin/fakemenot", line 11, in <module>
    load_entry_point('fakemenot==0.0.2', 'console_scripts', 'fakemenot')()
  File "build/bdist.linux-x86_64/egg/fakemenot/__init__.py", line 136, in main
  File "build/bdist.linux-x86_64/egg/fakemenot/__init__.py", line 45, in _do_ocr_and_lookup
  File "build/bdist.linux-x86_64/egg/pytesseract/pytesseract.py", line 122, in image_to_string
  File "build/bdist.linux-x86_64/egg/pytesseract/pytesseract.py", line 46, in run_tesseract
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I'm running this on lubuntu. The `subprocess.py` is existed.

**Comment by pwnfoo** [comment]
@Hori75 Did you install tesseract and tesseract data?

I think it's `tesseract-ocr` and `tesseract-ocr-eng` on Ubuntu.

**Comment by pwnfoo** [comment]
I have mentioned about this in the README file. It'll also make sense to add `sudo apt-get install tesseract-ocr tesseract-ocr-eng` to the installation instructions

Let me know if that works and I'll add it to the README file.

**Comment by Hori75** [comment]
I just installed `tesseract-ocr` and `tesseract-ocr-eng`. The other error occured.
```
Traceback (most recent call last):
  File "/usr/local/bin/fakemenot", line 11, in <module>
    load_entry_point('fakemenot==0.0.2', 'console_scripts', 'fakemenot')()
  File "build/bdist.linux-x86_64/egg/fakemenot/__init__.py", line 136, in main
  File "build/bdist.linux-x86_64/egg/fakemenot/__init__.py", line 59, in _do_ocr_and_lookup
UnboundLocalError: local variable 'potential_user' referenced before assignment
```

**Comment by pwnfoo** [comment]
@Hori75 That's kinda known. It happens when the OCR fails to find a valid twitter handle in the screenshot. I need to handle that properly in code. I'll do it soon :)
 Can you try another screenshot which is properly cropped? The program doesn't handle any cropping atm so make sure to screenshot like shown in the sample.

**Comment by Hori75** [comment]
I tested with a blurry tweet from the sample you made in `README.md` but that error occured. I didn't use any cropping tools. Also when I try it from the sample in `README.md`, it didn't show any output.

**Comment by pwnfoo** [comment]
@Hori75 Can you try again now? I have added a few commits to fix this. This should hopefully resolve the problems :)
