### ISSUE TITLE
Error running fakemenot

### ISSUE THREAD

**Issue by abhinavralhan** [sachinkamath/fakemenot#18]
fakemenot
Traceback (most recent call last):
  File "/home/abhinavralhan/miniconda3/bin/fakemenot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/abhinavralhan/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/home/abhinavralhan/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/home/abhinavralhan/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/home/abhinavralhan/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 660, in _build_master
  File "/home/abhinavralhan/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 968, in require
  File "/home/abhinavralhan/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'Pillow' distribution was not found and is required by pytesseract

**Comment by pwnfoo** [comment]
Check your installation. This is not an error thrown by `fakemenot`

Try `sudo pip uninstall fakemenot` , cd to fakemenot folder and do `sudo pip install -e .` to install it again.

**Comment by pwnfoo** [comment]
Closing this as it's not relevant to fakemenot. Please reopen if something else pops up :)
