### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by Hori75** [sachinkamath/fakemenot#19]
I tried to run fakemenot and this problem occured
```
Traceback (most recent call last):
  File "/usr/local/bin/fakemenot", line 11, in <module>
    load_entry_point('fakemenot==0.0.3', 'console_scripts', 'fakemenot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/fakemenot-0.0.3-py2.7.egg/fakemenot/__init__.py", line 67
    'consumer_key')..replace(
                    ^
SyntaxError: invalid syntax
```

**Comment by pwnfoo** [comment]
@Hori75 Sorry 'bout that. I ran `autopep8` tool and it did something stupid. Everything should be good now :)
