### ISSUE TITLE
Add more samples on README

### ISSUE THREAD

**Issue by pwnfoo** [sachinkamath/fakemenot#3]
It'll be nice to have a graphic representation of what works and what doesn't. 

Things to do : 
* Add a sample with a fake tweet.
* Add a sample with blurry text.

**Comment by Hori75** [comment]
I'd like to try.

**Comment by pwnfoo** [comment]
@Hori75 Please go ahead and send a PR when you are ready :)

**Comment by Hori75** [comment]
Sorry, but I got the problem while running fakemenot.
```
Traceback (most recent call last):
  File "/usr/local/bin/fakemenot", line 11, in <module>
    load_entry_point('fakemenot==0.0.2', 'console_scripts', 'fakemenot')()
  File "build/bdist.linux-x86_64/egg/fakemenot/__init__.py", line 136, in main
  File "build/bdist.linux-x86_64/egg/fakemenot/__init__.py", line 45, in _do_ocr_and_lookup
  File "build/bdist.linux-x86_64/egg/pytesseract/pytesseract.py", line 122, in image_to_string
  File "build/bdist.linux-x86_64/egg/pytesseract/pytesseract.py", line 46, in run_tesseract
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I'm running this at lubuntu. I need help.

**Comment by pwnfoo** [comment]
@Hori75 Can you please open a new issue for this?

**Comment by elahmo** [comment]
I have added some examples, but this issue is definitely present, I will open a new issue for this.
